"use client";
import Footer from "@/components/global/Footer";
import Navbar from "@/components/global/Navbar";
import { ChakraProvider } from "@chakra-ui/react";
import { SessionProvider } from "next-auth/react";
import "../app/styles/globals.css";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, session }) {
  return (
    <html
      lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
    >
      <head>
        <title>Virolife</title>
      </head>
      <body>
        <ChakraProvider>
          <SessionProvider>
            <Navbar />
            {children}
          </SessionProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
