"use client";
import Footer from "@/components/global/Footer";
import Navbar from "@/components/global/Navbar";
import { ChakraProvider } from "@chakra-ui/react";
import "../app/styles/globals.css";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>Virolife</title>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2480119685720701"
          crossorigin="anonymous"
        ></script>
      </head>
      <body>
        <ChakraProvider>
          {children}
          <script
            type="text/javascript"
            src="https://www.freevisitorcounters.com/auth.php?id=3ec73f1933e470581d15ee61c30ac054d0c29459"
          ></script>
          <script
            type="text/javascript"
            src="https://www.freevisitorcounters.com/en/home/counter/1063121/t/6"
          ></script>
        </ChakraProvider>
      </body>
    </html>
  );
}
