import Footer from "@/components/global/Footer"
import Navbar from "@/components/global/Navbar"
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Virolife</title>
      </head>
      <body>
          <Navbar />
          {children}
          <Footer />
      </body>
    </html>
  )
}
